import Complexe
import cat_dog
import count_hi
import double_char
import centered_average
import big_diff
import count_evens
import string_bits
import string_splosion
import front_times
import string_times
